===== Briser le plafond de glace

====== Fiche signalétique

[cols="1,2"]
|===

|Lien
|https://cfp.devoxx.fr/2023/talk/MVJ-2885/Briser_le_plafond_de_glace

|Type/format de présentation
|Keynote, 20mn

|Track
|People & Culture, Soft Skills, Future of work, Innovation, Side projects

|Niveau de la présentation
|débutant

|Mots-clés 	
|team inspiration optimizations

|===

====== Speaker

Marion Poitevin

====== Notes

Elle a fait que des jobs où il n'y avait pas de femme.

Equipe national féminisme d'alpinisme haut niveau

Groupe militaire de haute montagne, 1ère femme, elle a tenté.

Fausses croyances sur les hommes (surtout le commandant), il l'a sexualisé.

--- 
Important : la team. Cheffe d'expé, n'aurait jamais pu arriver autrement (en vacances). Tout se bidouille bien quand tu es avec les bonnes personnes.

Ensuite instructeur à l'EMHM. Encore sur la scellette mais les RH Paris ont dit, vu le CV... Quand passer sous-off, on lui dit je sais pas si tu as le potentiel. Isolée, les blagues sont différentes...

Dans la police, forte médiatisation pour recruter des femmes

Prof à l'ENSEA. Discrimination positive mais après vous partez pour faire des bébés.

Partenaires matériel : Petzl, Millet. Enceinte, on va baisser ta dotation.
 	
--- S'entrainer, échouer, s'entrainer.

On part du principe que tous les hommes sont plus forts que toutes les femmes


Les clichés sexistes sont ancrés, c'est dur d'aller au dessus.

Démarche très sportive mais avec cet été très chaud, on se rend compte que certaines choses disparaissent. Certaine nostalgie.

Livre : briser le plafon de glace
